name: Continuous Integration

on:
  pull_request:
  push:
    branches: 
      - develop
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python
        uses: actions/setup-python@v2.2.1
      - name: Install pytest
        run: pip install pytest
      - name: Run test.
        run: pytest tests/